apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-eures-cv-eksport-proxy
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 80
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 2
  cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 256Mi
  accessPolicy:
    outbound:
      rules:
        - application: pam-eures-cv-eksport
  env:
    - name: EURES_PROXIED_URL
      value: "http://pam-eures-cv-eksport.teampam/pam-eures-cv-eksport"
    - name: EURES_PROXIED_HOST
      value: "pam-eures-cv-eksport.teampam"
    - name: EURES_PROXIED_PORT
      value: "80"
  ingresses:
    - {{ ingress }}