micronaut:
  application:
    name: proxy
  server:
    context-path: /pam-eures-cv-eksport
    port: 9031


pam-eures-cv-eksport:
  scheme: http
  host: ${EURES_PROXIED_HOST:localhost}
  port: ${EURES_PROXIED_PORT:9030}