name: CI
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - '*'
      - '!main'
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses:  snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build and test
        run: docker build .