name: deploy-prod
on:
  release:
    types: [published]

env:
  VERSION_TAG: ${{ github.event.release.tag_name }}

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.VERSION_TAG }}
      - uses: nais/deploy/actions/deploy@v2
        name: deploy to prod-gcp
        env:
          CLUSTER: prod-gcp
          RESOURCE: naiserator.yml
          VARS: naiserator-prod.json
      - name: post-production
        uses: navikt/pam-deploy/actions/post-production@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
