name: deploy-prod
on:
  release:
    types: [published]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: get release tag
        env:
          VERSION_TAG: ${{ github.event.release.tag_name }}
        run: |
          APPLICATION=$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)
          IMAGE=ghcr.io/$GITHUB_REPOSITORY/$APPLICATION:$VERSION_TAG
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo $IMAGE
      - uses: nais/deploy/actions/deploy@v2
        name: deploy to prod-gcp
        env:
          CLUSTER: prod-gcp
          RESOURCE: naiserator.yml
          VARS: naiserator-prod.json
      - name: post-production
        uses: navikt/pam-deploy/actions/post-production@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
