name: build-deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      id-token: write
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: pre-deploy
        uses: navikt/pam-deploy/actions/pre-deploy@v7
        env:
          DRAFTS_MAX: 10
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          TEAM: teampam
      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teampam
          tag: ${{ env.VERSION_TAG }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          dockerfile: Dockerfile
          build_args: |
            "VERSION_TAG=${{ env.VERSION_TAG }}"
      - name: deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: naiserator.yml
          VARS: naiserator-dev.json
      - name: post-deploy
        uses: navikt/pam-deploy/actions/post-deploy@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: draft release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.VERSION_TAG }}
          name: ${{ env.APPLICATION }} ${{ env.VERSION_TAG }}
          body: ${{ env.CHANGE_LOG }}
          draft: true
          prerelease: false